server:
  address: localhost
  port: 8080

spring:

  main:
    allow-bean-definition-overriding: true

  jpa:
    database: mysql
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
      format_sql: true