server:
  address: localhost
  port: 8080

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/mint1?characterEncoding=UTF-8&serverTimezone=UTC

    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password

  jpa:
    database: mysql
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
      format_sql: true